import { createFutureUniversePack, type FutureUniverseSpec } from '../future-pack'

const kindling = (name: string, flavor: string, silhouette: string) => ({ name, flavor, silhouette })
const archive = (name: string, glyph: string, observation: string, implication: string, effect: string, silhouette: string) => ({ name, glyph, observation, implication, effect, silhouette })
const story = (title: string, provenance: string, text: string) => ({ title, provenance, text })

export const TEMPEST_SPEC: FutureUniverseSpec = {
  id: 'tempest', prefix: 'u6', name: 'Tempest', shortName: 'Tempest', epithet: 'The Charged Expanse',
  premise: 'Rebuild a universe of atmosphere, pressure, magnetism, and storms that create land through deliberate discharge.',
  primaryVerb: 'discharge', question: 'Is power safest when contained, or only meaningful when released?',
  currency: 'Charge', currencyGlyph: 'ϟ', currencyMaterial: 'separated electrical potential carried through cloud cells and plasma leaders',
  heartName: 'Storm Eye', heartPhenomenon: 'A calm pressure aperture surrounded by a rotating wall of separated charge.',
  heartSilhouette: 'open eye-wall spiral with three branching leaders and a calm hexagonal center',
  heartVerb: 'separates charge and advances one labeled leader', achievementPower: 'Potential',
  epochName: 'Grounding', epochMatter: 'Fulgurites', epochMatterSingular: 'Fulgurite', epochGlyph: '↯',
  epochMaterial: 'glassed discharge paths that preserve the storm’s chosen route',
  archiveName: 'Storm Almanac', archiveGlyph: '☈',
  archiveRecord: 'MAP OF THE FINAL CLIMATE — GROUNDING NOTE\n\nWe stored every disagreement as weather because containment looked peaceful from inside the Eye. Pressure is still motion. Silence is still a forecast.\n\nRelease before the path chooses itself. Leave the fulgurite where the next storm can read it.\n\n— last keeper of the planetary dynamo',
  palette: { accentHue: 202, bg: '#050b12', accent: '#70c9ee', gold: '#e3f7ff', panel: 'rgba(8, 22, 34, 0.88)' },
  visualMaterials: ['cloud volume', 'rain filament', 'ice crystal', 'plasma channel', 'magnetic field line', 'stormglass', 'glassed sand'],
  primarySilhouettes: ['a bounded potential field joining six storm cells', 'a branching continental front with declared discharge paths', 'a stable auroral column occupying a former eye wall'],
  economy: {
    baseCosts: [15, 166, 2_288, 22_880, 358_400, 5_120_000, 55_080_000, 884_000_000, 9_000_000_000, 38_000_000_000, 1_700_000_000_000, 14_000_000_000_000, 120_000_000_000_000, 1_000_000_000_000_000, 8_500_000_000_000_000, 73_000_000_000_000_000, 630_000_000_000_000_000, 5_500_000_000_000_000_000],
    baseRates: [0.336, 2.565, 25.3, 276.75, 1_837.5, 22_785, 178_350, 1_236_000, 16_280_000, 118_400_000, 1_281_250_000, 9_275_000_000, 101_250_000_000, 974_100_000_000, 7_360_000_000_000, 77_000_000_000_000, 740_250_000_000_000, 7_790_000_000_000_000],
    costMultiplier: 1.16,
  },
  signatureUpgrades: (generators) => [
    { id: 'u6-capacitive-rain', name: 'Capacitive Rain', flavor: 'Every falling layer carries a measured difference downward.', cost: 3e7, glyph: '⌇', hue: 202, unlock: { gen: generators[4].id, count: 10 }, effects: [{ kind: 'synergy', gen: generators[4].id, per: generators[1].id, value: 0.018 }] },
    { id: 'u6-declared-grounding', name: 'Declared Grounding', flavor: 'A path disclosed in advance can carry a larger share safely.', cost: 9e10, glyph: '↯', hue: 188, unlock: { clicks: 1_200 }, effects: [{ kind: 'clickShare', value: 0.018 }, { kind: 'critMult', value: 1.5 }] },
    { id: 'u6-auroral-return', name: 'Auroral Return', flavor: 'Released charge comes home as circulation instead of impact.', cost: 6e16, glyph: '⌒', hue: 224, unlock: { gen: generators[15].id, count: 10 }, effects: [{ kind: 'globalMult', value: 1.7 }, { kind: 'critChance', value: 0.03 }] },
  ],
  kindlings: [
    kindling('Ion', 'One separated charge waits for a path.', 'paired positive and negative marks inside a cloudlet'),
    kindling('Droplet Charge', 'Falling water carries potential between layers.', 'teardrop split by a short charge bar'),
    kindling('Static Veil', 'A broad field makes every raised edge attentive.', 'hatched curtain with three upright filaments'),
    kindling('Updraft', 'Warm air turns stored difference into height.', 'rising spiral arrow through a cloud base'),
    kindling('Rain Cell', 'A small weather system learns circulation.', 'stacked cloud and rain comb inside a closed cell'),
    kindling('Thunderhead', 'The first anvil holds enough charge to make a decision.', 'cumulonimbus tower with anvil cap and two leaders'),
    kindling('Lightning Leader', 'A path explores the air without pretending it is random.', 'branching stepped leader with numbered forks'),
    kindling('Hail Forge', 'Ice collisions separate charge with industrial patience.', 'layered hail rings inside a convection column'),
    kindling('Supercell', 'Rotation lets a storm remember its own unfinished path.', 'hooked rotating cell with a bounded core'),
    kindling('Jet Stream', 'A river of air carries decisions across the horizon.', 'long ribbon with alternating pressure chevrons'),
    kindling('Cyclone Pair', 'Two storms exchange angular momentum without merging.', 'counter-rotating spiral pair joined by a saddle line'),
    kindling('Aurora Crown', 'The magnetosphere answers discharge in folded light.', 'three auroral curtains above a polar oval'),
    kindling('Continental Front', 'Weather becomes geography written in pressure.', 'sweeping front with alternating triangle and semicircle marks'),
    kindling('Storm Ocean', 'Every cell participates in one planetary circulation.', 'layered wave field beneath a rotating storm band'),
    kindling('Planetary Dynamo', 'The world makes its own magnetic shelter.', 'nested magnetic loops around a split core'),
    kindling('Magnetosphere', 'Charged paths bend before they become impacts.', 'asymmetric field shell with a long night-side tail'),
    kindling('The Endless Hurricane', 'Containment perfected itself into a prison of motion.', 'multi-wall cyclone with one open evacuation seam'),
    kindling('The Second Thunder', 'The storm answers itself, then chooses where to stop.', 'vertical discharge column ending in a branching fulgurite crown'),
  ],
  archives: [
    archive('First Raindrop', '◉', 'One drop contains a pressure map of the whole future storm.', 'Its layers formed before Tempest had an atmosphere.', 'improves initial potential gain', 'large drop with three nested pressure contours'),
    archive('Bottled Petrichor', '♧', 'The scent of rain exists before any ground is wet.', 'Memory of release can precede the event it promises.', 'forecasts the next ready discharge', 'stoppered vial above cracked ground marks'),
    archive('Fulgurite Branch', '↯', 'Sand remembers exactly where lightning became earth.', 'The branch records choice more honestly than the old political archives.', 'strengthens Grounding yield', 'forked glass root with five path scars'),
    archive('Red Sprite Photograph', '⋔', 'A high-altitude discharge blooms above the storm instead of below.', 'The image was exposed by a signal from Canticle.', 'reveals upper-atmosphere Omens', 'three vertical sprite tendrils over a cloud line'),
    archive('Ball-Lightning Cage', '⊙', 'A luminous sphere follows the last completed path.', 'The cage is a map, not a prison; every bar names an exit.', 'repeats part of the prior discharge reward', 'orb inside an open six-bar cage'),
    archive('Compass Without North', '⌖', 'Its needle points toward maximum potential difference.', 'North disappeared when the dynamo became partisan.', 'labels efficient discharge direction', 'four-point compass with a split diagonal needle'),
    archive('Eye-Wall Seed', '◌', 'A tiny spiral contains the pressure rules of a mature cyclone.', 'Storms were planted deliberately as civic infrastructure.', 'accelerates long-path charge', 'spiral seed with an open calm center'),
    archive('Frozen Thunder', '▧', 'A pressure wave stands still inside clear ice.', 'The trapped sound is safe only because the fracture path is visible.', 'extends safe discharge duration', 'ice block crossed by a frozen zigzag waveform'),
    archive('Aurora Ribbon', '⌒', 'A magnetic curtain writes the same route in light and field direction.', 'Clockwork once scheduled these curtains as interworld signals.', 'improves Jetstream circulation', 'folded ribbon above three magnetic ticks'),
    archive('Jetstream Chart', '⇝', 'Every fast current is drawn with entry, load, and exit.', 'The chart treats weather as a public route rather than fate.', 'unlocks saved automation thresholds', 'long band with four labeled gates'),
    archive('Stormglass Barometer', '◇', 'Crystals grow into the shape of tomorrow’s pressure.', 'Prediction did not prevent the final storm because nobody agreed to act.', 'adds exact charge and time forecasts', 'diamond vial holding three crystal weather fronts'),
    archive('Map of the Final Climate', '☈', 'Every stored conflict converges on one planetary eye.', 'A disagreement became extinction only after the culture made release impossible.', 'completes Aftermath and reveals the Beacon route', 'world disk crossed by one branching path to an auroral column'),
  ],
  shelfNames: ['Formation', 'Discharge', 'Aftermath'],
  shelfRewards: ['Storm cells build potential more clearly and efficiently.', 'Chosen paths produce stronger bounded releases.', 'Fulgurites preserve route knowledge through every Grounding.'],
  omens: [
    { name: 'Ball Lightning', description: 'Follow the previous discharge path to recover a bounded portion of its energy.', silhouette: 'luminous orb moving along a forked route', motion: 'atmospheric', effects: [{ kind: 'clickShare', value: 0.008 }] },
    { name: 'Blue Jet', description: 'A vertical path rewards infrastructure linking cloud and horizon.', silhouette: 'narrow upward cone from thunderhead to ionosphere', motion: 'atmospheric', effects: [{ kind: 'globalMult', value: 1.15 }] },
    { name: 'Sprites', description: 'Several high-altitude targets form a timed shape-and-number pattern.', silhouette: 'three branching tendrils above a shared cloud line', motion: 'atmospheric', effects: [{ kind: 'critChance', value: 0.025 }] },
    { name: 'Quiet Eye', description: 'A rare calm interval banks production and reveals an Almanac record.', silhouette: 'open circular calm surrounded by a broken eye wall', motion: 'still', effects: [{ kind: 'globalMult', value: 1.1 }, { kind: 'clickMult', value: 1.1 }] },
  ],
  doctrines: [
    { name: 'Conductor', description: 'Favor frequent, reliable short discharges.', favoredMotivations: ['performer', 'optimizer'], visualSignature: 'short bright leader ending in a compact fulgurite', effects: [{ kind: 'clickShare', value: 0.008 }] },
    { name: 'Supercell', description: 'Hold long charge cycles for enormous branching chains.', favoredMotivations: ['performer', 'wayfinder'], visualSignature: 'rotating multi-cell wall with one long leader route', effects: [{ kind: 'globalMult', value: 1.16 }] },
    { name: 'Jetstream', description: 'Favor passive circulation, offline gain, and cross-cell flow.', favoredMotivations: ['restorer', 'optimizer'], visualSignature: 'broad horizon ribbon linking every pressure cell', effects: [{ kind: 'globalMult', value: 1.1 }, { kind: 'synergyMult', value: 1.08 }] },
    { name: 'Stormchaser', description: 'Favor active Omens, critical routes, and archive variants.', favoredMotivations: ['performer', 'archivist'], visualSignature: 'branching path with numbered observation stations', effects: [{ kind: 'clickMult', value: 1.25 }, { kind: 'critChance', value: 0.02 }] },
  ],
  lumen: {
    awake: 'The Eye is calm because the storm is listening. The charge around it is not asleep.',
    first: 'One Ion, one difference, no impact yet. Potential is a question with time to answer.',
    law: 'A longer leader touches more of the world. A riskier branch returns more power and leaves less room for error.',
    civil: 'The Hail Forge made weather into public infrastructure. They knew every storm had authors.',
    archive: 'The Storm Almanac keeps paths, not excuses. Every fulgurite names where stored power finally went.',
    omen: 'Ball lightning is following an old decision home. Consequences have better memory than institutions.',
    epoch: 'Grounding left a Fulgurite: not a trophy, but a route the next storm will not have to invent blindly.',
    cosmic: 'The Storm Ocean circulates one atmosphere through regions that once called their pressure private.',
    question: 'How long can restraint remain a virtue after containment becomes the danger?',
    beacon: 'The Auroral Column releases upward, returns gently, and keeps the path visible. Power learned a boundary.',
  },
  story: [
    story('The First Difference', 'measured between two ions in the Storm Eye', 'The first storm began when two charges agreed not to cancel immediately. The record calls the space between them potential: neither violence nor peace, only the capacity for a path. Early keepers taught children to read that distinction before they taught weather.'),
    story('Public Ground', 'municipal fulgurite marker beside a rain cistern', 'Every district maintained safe places for disagreement to become visible action. A discharge had entry, path, load, and ground. The glass branch remained afterward so nobody could pretend the released power had appeared without a cause.'),
    story('The Four Paths', 'Storm Almanac training plate with raised route marks', 'Conductor, Supercell, Jetstream, Stormchaser. Four routes share one bounded meter and disclose their thresholds before commitment. The plate warns that choosing a short path is not cowardice, and holding charge is not wisdom when the containment itself has begun to fail.'),
    story('Weather Parliament', 'minutes encoded as pressure isobars', 'Debate altered the atmosphere literally. Speakers stored objections as charge so no argument would cause immediate harm. The sky became calm, then heavy, then permanently dark. A culture designed to defer violence forgot that delay also requires a path toward resolution.'),
    story('The Quiet Eye', 'a complete minute of zero wind preserved in stormglass', 'Inside the calm, every instrument worked and nobody spoke. The silence felt safe enough that leaders extended it by another hour, then a season. Beyond the wall, pressure kept accumulating. The Eye did not create the disaster. It made the disaster easy not to see.'),
    story('Ball Lightning Census', 'open-cage registry of wandering charged bodies', 'The census tracked each sphere by its inherited path rather than appearance. None moved randomly. Each was a consequence detached from the decision that produced it, returning until someone completed the grounding the original discharge had avoided.'),
    story('Grounding Procedure', 'etched along a branching glass root', 'Release the whole storm through a declared path. Return Charge, cells, ordinary works, and buy mode. Preserve Fulgurites, the Almanac, story, trials, and deeper law. Show what returns and what remains. A Grounding without an inspected path is classified as impact.'),
    story('The Final Disagreement', 'pressure front spanning the planetary archive', 'Two neighbors disputed how much power one region could store for another. Neither discharged. Containment became virtue, compromise became delay, and delay became the largest potential difference the atmosphere had ever held. One ordinary dissent then supplied the final leader.'),
    story('Lumen Counts the Branches', 'annotation beneath the Fulgurite Branch', 'Lumen traces the final path backward and names every choice that shaped it. “Catastrophe likes to pose as weather,” they write. “A path is less frightening when nobody owns it.” The next line is crossed out but readable: “I once called an awakening inevitable.”'),
    story('The Stable Column', 'broadcast from the Second Thunder Beacon', 'The final discharge rises instead of striking ground. Charge circulates through the auroral column, returns gently, and never requires the world to pretend potential is gone. Power continues because release has boundaries, witnesses, and a route back into relationship.'),
  ],
  physics: { randomAllowed: true, charge: { minimumPathLength: 1, maximumPathLength: 8, overflowBehavior: 'hold', automationUsesSavedPaths: true } },
  trials: [
    { name: 'Short Circuit', failure: 'The quickest path ignored every system it crossed.', rule: 'use only Conductor discharges', accessibility: 'Charge, threshold, and path length are announced as text.', rewardEffects: [{ kind: 'clickShare', value: 0.002 }] },
    { name: 'Held Storm', failure: 'Potential was mistaken for harmless storage.', rule: 'reach ninety percent charge before every discharge', accessibility: 'Meter fill includes percentage and ten notched segments.', rewardEffects: [{ kind: 'globalMult', value: 1.03 }] },
    { name: 'Broken Leader', failure: 'One missing cell forced the path to become deliberate.', rule: 'discharge with alternating Kindling tiers', accessibility: 'Available cells have numbered shape markers.', rewardEffects: [{ kind: 'critChance', value: 0.01 }] },
    { name: 'Quiet Eye', failure: 'Calm concealed a dangerous pressure gradient.', rule: 'complete without active Omens', accessibility: 'Calm state uses an open ring and explicit status text.', rewardEffects: [{ kind: 'clickMult', value: 1.05 }] },
    { name: 'Three Strikes', failure: 'The civilization used repeated force instead of a better route.', rule: 'reach the target in at most three discharges', accessibility: 'Remaining discharge count is persistently announced.', rewardEffects: [{ kind: 'critMult', value: 1.25 }] },
    { name: 'Aftermath', failure: 'Nobody preserved the evidence left in glassed ground.', rule: 'finish with all three Almanac shelves complete', accessibility: 'Shelf completion uses names, fractions, and distinct icons.', rewardEffects: [{ kind: 'globalMult', value: 1.08 }] },
  ],
  tempo: 108, meter: '4/4 syncopated pressure cycle',
  audioFamilies: ['dry static snap', 'rising pressure interval', 'contained electrical crack', 'distant storm call', 'grounding leader-to-fulgurite cadence'],
  silenceState: 'Charge percentage, notched meter, path shape, countdown, and captions carry every mechanical signal.',
  fatiguePolicy: 'Electrical highs are tightly limited; overlapping discharges duck rain and thunder beds; no cue exceeds the semantic loudness ceiling.',
  routeGlyph: '☈', routeArrival: 'a calm aperture opens inside a storm whose every leader points away from the Heart', unlockText: 'light Prismata’s Beacon',
  beaconName: 'Auroral Column Beacon', beaconSilhouette: 'stable vertical auroral column rising from a branching fulgurite into two magnetic loops', beaconReward: 5,
  nonColorSignals: [
    { id: 'u6-building', text: 'potential building', shape: 'open segmented ring', pattern: 'ascending numbered notches' },
    { id: 'u6-ready', text: 'path ready', shape: 'closed ring with outward fork', pattern: 'bold threshold mark' },
    { id: 'u6-discharging', text: 'discharge propagating', shape: 'branching leader', pattern: 'numbered path sequence' },
    { id: 'u6-calm', text: 'quiet eye', shape: 'empty center ring', pattern: 'unbroken outer wall' },
  ],
}

const packs = createFutureUniversePack(TEMPEST_SPEC)
export const TEMPEST = packs.legacy
export const TEMPEST_V2_PACK = packs.v2
