import { createFutureUniversePack, type FutureUniverseSpec } from '../future-pack'

const kindling = (name: string, flavor: string, silhouette: string) => ({ name, flavor, silhouette })
const archive = (name: string, glyph: string, observation: string, implication: string, effect: string, silhouette: string) => ({ name, glyph, observation, implication, effect, silhouette })
const story = (title: string, provenance: string, text: string) => ({ title, provenance, text })

export const CANTICLE_SPEC: FutureUniverseSpec = {
  id: 'canticle', prefix: 'u7', name: 'Canticle', shortName: 'Canticle', epithet: 'The Silent Choir',
  premise: 'Restore a universe whose matter exists as standing waves, memory loops, rests, and relationships between distinct voices.',
  primaryVerb: 'compose', question: 'Can a voice remain itself while becoming part of a harmony?',
  currency: 'Resonance', currencyGlyph: '◌', currencyMaterial: 'standing-wave energy carried through membranes, strings, chambers, and deliberate rests',
  heartName: 'First Chord', heartPhenomenon: 'A resonant membrane whose visible nodes hold several relationships without becoming a decorative note.',
  heartSilhouette: 'tensioned hexagonal membrane with four standing-wave nodes and one open rest interval',
  heartVerb: 'deforms the membrane and propagates one visible waveform through the active measure', achievementPower: 'Voice',
  epochName: 'Refrain', epochMatter: 'Overtones', epochMatterSingular: 'Overtone', epochGlyph: '≋', epochMaterial: 'preserved harmonic relationships surviving the completed measure',
  archiveName: 'Resonant Memory', archiveGlyph: '⌇',
  archiveRecord: 'INSTRUMENT FOR A SECOND VOICE — PERFORMANCE NOTE\n\nPerfect harmony made every citizen indistinguishable from the whole. We called the result peace because nobody could hear dissent.\n\nLeave rests. Keep the source labels. Let another voice answer without becoming yours.\n\n— last conductor of the Silent Choir',
  palette: { accentHue: 328, bg: '#0c0710', accent: '#d89bc7', gold: '#fff0f7', panel: 'rgba(27, 12, 28, 0.88)' },
  visualMaterials: ['resonant wood', 'tensioned membrane', 'Chladni sand', 'metallic overtone', 'luminous air density', 'string fiber', 'waveform ribbon'],
  primarySilhouettes: ['a four-slot visible measure around a resonant membrane', 'a cathedral of chambers joined by standing-wave nodes', 'two distinct waveform voices sharing one open horizon'],
  economy: {
    costScales: [0.78, 0.92, 1.05, 0.9, 1.12, 1.22, 1.38, 1.3, 1.55, 1.72, 1.9, 1.82, 2.15, 2.4, 2.7, 3.05, 3.45, 4.1],
    rateScales: [0.8, 1.1, 0.92, 1.25, 1.05, 1.32, 1.18, 1.48, 1.3, 1.58, 1.72, 1.45, 1.88, 2.05, 2.2, 2.42, 2.7, 3.25],
    costMultiplier: 1.14,
  },
  signatureUpgrades: (generators) => [
    { id: 'u7-open-measure', name: 'Open Measure', flavor: 'A bounded rest gives the next pulse somewhere to arrive.', cost: 2e7, glyph: '◌', hue: 328, unlock: { gen: generators[3].id, count: 10 }, effects: [{ kind: 'synergy', gen: generators[3].id, per: generators[0].id, value: 0.016 }] },
    { id: 'u7-counterpoint-gate', name: 'Counterpoint Gate', flavor: 'The mechanism opens only when two unlike sources remain audible.', cost: 7e10, glyph: '≋', hue: 304, unlock: { gen: generators[10].id, count: 10 }, effects: [{ kind: 'synergy', gen: generators[10].id, per: generators[6].id, value: 0.014 }, { kind: 'synergyMult', value: 1.15 }] },
    { id: 'u7-room-for-answer', name: 'Room for an Answer', flavor: 'The completed architecture reserves one interval it cannot fill itself.', cost: 4e16, glyph: '⋈', hue: 348, unlock: { gen: generators[16].id, count: 10 }, effects: [{ kind: 'globalMult', value: 1.65 }, { kind: 'clickShare', value: 0.012 }] },
  ],
  kindlings: [
    kindling('Pulse', 'One event proves that time can carry shape.', 'filled node followed by three open timing marks'),
    kindling('Reed Breath', 'Air learns to sustain without becoming noise.', 'tapered breath ribbon through a split reed frame'),
    kindling('String', 'Tension turns distance into relationship.', 'long bowed curve with two fixed end nodes'),
    kindling('Drum Skin', 'A surface remembers where it was touched.', 'round membrane crossed by one nodal diameter'),
    kindling('Tuning Fork', 'Two arms disagree at exactly the same rate.', 'fork silhouette with paired propagation arcs'),
    kindling('Resonant Bowl', 'A vessel gives decay somewhere meaningful to live.', 'open bowl with three nested overtone rings'),
    kindling('Echo Chamber', 'A return becomes useful when its path is inspectable.', 'faceted chamber with an offset response contour'),
    kindling('Bell Garden', 'Many bodies share air without sharing one pitch.', 'four unequal bells suspended from one open frame'),
    kindling('Harmonic Loom', 'Relationships are woven across rests as well as sounds.', 'crossed strings on a four-slot rectangular loom'),
    kindling('Memory Organ', 'A sustained voice carries the shape of prior measures.', 'three vertical pipes above a looping air reservoir'),
    kindling('Counterpoint Pair', 'Two sources answer without collapsing into unison.', 'interleaved wave ribbons with separate node shapes'),
    kindling('Choir Constellation', 'Distant voices become navigable relationships.', 'seven nodes linked by alternating pulse and rest lines'),
    kindling('Cathedral Wave', 'Architecture is built around what sound needs to become legible.', 'vaulted chamber crossed by a standing-wave spine'),
    kindling('Planetary Chorus', 'Continents exchange pulse, drone, and silence.', 'world disk divided into four waveform provinces'),
    kindling('Gravitational Hymn', 'Mass itself keeps a slow relationship across the dark.', 'two lensing arcs modulated by a long wave'),
    kindling('World Resonator', 'The entire horizon becomes an instrument with boundaries.', 'broad frame surrounding eight labeled antinodes'),
    kindling('The Unheard Movement', 'What no ear detects remains complete in shape and time.', 'dark waveform bordered by captions and tactile notch marks'),
    kindling('The Second Voice', 'The universe answers without imitating the first.', 'two distinct waveform profiles meeting at one open rest'),
  ],
  archives: [
    archive('First Drum Skin', '◉', 'A membrane preserves the handprint of its first careful strike.', 'The oldest rhythm began as reassurance, not command.', 'improves pulse clarity', 'round membrane with one hand-shaped nodal gap'),
    archive('Bell Without Metal', '◇', 'A bell-shaped pressure field rings with no solid body.', 'Its outline matches a Pressure Bell in Tidefall.', 'strengthens sustained roles', 'open bell contour made from three air-density bands'),
    archive('Fossilized Chord', '⋔', 'Several vibrations are fixed inside layered stone.', 'The chord remained plural after every instrument decayed.', 'preserves measure state through Refrain', 'stone slab with three intersecting wave grooves'),
    archive('Silent Tuning Fork', 'Ψ', 'The fork produces a complete node pattern and no audible tone.', 'Silence is not an accessibility fallback here; it is an authored voice.', 'unlocks full silent equivalence', 'fork surrounded by four numbered nodal points'),
    archive('Whale-Song Cylinder', '∿', 'A spiral groove contains calls from an ocean without this sky.', 'Tidefall and Canticle once exchanged migration songs.', 'improves echo roles', 'wax cylinder wrapped by a long waveform groove'),
    archive('Seismic Hymn', '≋', 'A planet sings below every audible range.', 'The old choir excluded it until foundations began answering.', 'strengthens drone and offline measures', 'layered ground profile crossed by a slow waveform'),
    archive('Glass Harmonica Moon', '◒', 'A crescent of tuned glass rotates through distinct overtones.', 'The moon was built to let Prismata’s bands become harmony without losing labels.', 'improves counterpoint', 'crescent of nested glass disks with separate hatch marks'),
    archive('Echo of Lumen', '⌁', 'A voice says “continue” before Lumen remembers speaking.', 'The archive may be preserving possible relationships, not recorded sound.', 'reveals alternate story annotations', 'offset speech waveform returning through a small aperture'),
    archive('Broken Conductor’s Baton', '╱', 'The baton snapped where direction became control.', 'Afterward the choir kept time by watching one another breathe.', 'strengthens free measure changes', 'two separated baton halves bridged by timing marks'),
    archive('Chladni Star Map', '※', 'Sand nodes form a sky navigable in total silence.', 'Every constellation is also a route through the Resonant Memory.', 'improves visual timing', 'square plate with four distinct nodal regions'),
    archive('Rest Between Universes', '◌', 'A measured silence lasts exactly as long as a Crossing.', 'The Dark Between may be a rest placed deliberately in a larger composition.', 'amplifies strategic rests', 'empty bar enclosed by two waveform brackets'),
    archive('Instrument for a Second Voice', '⋈', 'An unfinished chamber has two entrances and no central podium.', 'The civilization designed it only after perfect harmony had erased everyone who might use it.', 'completes Relationship and reveals the Beacon route', 'paired resonators sharing one open central rest'),
  ],
  shelfNames: ['Voice', 'Memory', 'Relationship'],
  shelfRewards: ['Pulse and sustain roles become more expressive without increasing required input.', 'Echoes and drones preserve useful structure while absent.', 'Counterpoint and rests gain a capstone bonus when multiple voices remain distinct.'],
  omens: [
    { name: 'Wandering Refrain', description: 'Repeat a short pattern using audio, shape, or text timing with equivalent rewards.', silhouette: 'four-node phrase moving between two chambers', motion: 'waveform', effects: [{ kind: 'clickMult', value: 1.2 }] },
    { name: 'Dissonant Visitor', description: 'Resolve one conflicting interval by choosing a compatible relationship.', silhouette: 'two crossing wave ribbons separated by an open node', motion: 'waveform', effects: [{ kind: 'synergyMult', value: 1.12 }] },
    { name: 'Choir of One', description: 'The weakest Kindling temporarily carries the visible lead without erasing others.', silhouette: 'one bright source surrounded by six outlined responders', motion: 'waveform', effects: [{ kind: 'globalMult', value: 1.14 }] },
    { name: 'Perfect Rest', description: 'Intentionally do nothing for a few seconds while the reward grows visibly.', silhouette: 'empty measure bracket with an expanding border', motion: 'still', effects: [{ kind: 'clickShare', value: 0.008 }] },
  ],
  doctrines: [
    { name: 'Pulse', description: 'Favor active timing and rapid repeating measures.', favoredMotivations: ['performer', 'optimizer'], visualSignature: 'filled downbeat nodes alternating with sharp response arcs', effects: [{ kind: 'clickMult', value: 1.3 }] },
    { name: 'Drone', description: 'Favor stable passive and offline production.', favoredMotivations: ['restorer', 'optimizer'], visualSignature: 'long sustained bands beneath a slowly changing nodal field', effects: [{ kind: 'globalMult', value: 1.13 }] },
    { name: 'Counterpoint', description: 'Favor interactions between several Kindling families.', favoredMotivations: ['optimizer', 'archivist'], visualSignature: 'two distinct ribbons crossing without merging their source marks', effects: [{ kind: 'synergyMult', value: 1.22 }] },
    { name: 'Silence', description: 'Favor rests, delayed rewards, Archives, and Deep efficiency.', favoredMotivations: ['restorer', 'archivist'], visualSignature: 'open timing spaces framed by amplified neighboring waves', effects: [{ kind: 'globalMult', value: 1.08 }, { kind: 'clickShare', value: 0.006 }] },
  ],
  lumen: {
    awake: 'The membrane answered with more than one contour. Listen—or watch. Neither reading is secondary here.',
    first: 'A Pulse is an event with edges. It does not become rhythm until something else is allowed to answer.',
    law: 'Sixteen places, six roles, and no compulsory note. The rests are editable because silence must be chosen to mean anything.',
    civil: 'The Bell Garden shares one air and keeps every body distinct. Harmony began as coexistence, not correction.',
    archive: 'Resonant Memory records sources and intervals separately. A flawless waveform is not proof that a singer remained.',
    omen: 'The refrain returned altered. Good. Repetition that cannot admit change is only enforcement with a melody.',
    epoch: 'A Refrain preserved the relationships that survived the measure as Overtones—not the notes, and not their obedience.',
    cosmic: 'The Planetary Chorus has no podium. Continents exchange pulse, drone, and silence across an open score.',
    question: 'If harmony requires a voice to become indistinguishable, who is left to hear it?',
    beacon: 'The Second Voice answers in a contour the first did not predict. Canticle leaves the next rest open.',
  },
  story: [
    story('The First Chord', 'node pattern preserved in the Heart membrane', 'Several vibrations met and remained distinguishable. The record calls this a chord because relationship, not simultaneity, made it meaningful. One early annotator adds that the empty interval after the sound mattered equally: without room to answer, a voice is only occupation.'),
    story('Civic Measures', 'public score written in shapes, captions, and raised marks', 'The first measures used four slots so every citizen could anticipate the whole cycle. Later composers expanded to eight and sixteen, but the public grid never disappeared. Sound enriched the state; it never owned the instructions or the reward.'),
    story('The Positive Rest', 'teaching plate from a Bell Garden', 'Students were told not to treat a rest as missing content. A rest stores attention, separates causes, and amplifies neighboring relationships. The plate depicts silence as an open bounded object rather than blank space. Someone has polished the rest marker more often than the notes.'),
    story('Two Voices at the Gate', 'counterpoint etched into opposite door frames', 'Each traveler sang a different route through the city. The gate opened only when both lines remained audible and their rests aligned. Unison failed. The mechanism was built to prove cooperation did not require anyone to become easier to ignore.'),
    story('The Silent Conservatory', 'performance archive with no audio track', 'Every timing, source, and harmonic relation is preserved through expanding nodes, captions, and tactile marks. The curators considered this an ordinary complete recording. Centuries later, leaders called silent equivalence wasteful because it made centralized performance less necessary.'),
    story('The Perfect Conductor', 'baton fragments recovered beneath the Memory Organ', 'The conductor could hear every voice and gradually corrected every difference. Tuning improved. Error disappeared. So did improvisation, accent, dissent, and eventually the ability to tell whether any singer remained behind the flawless output.'),
    story('Refrain Procedure', 'final bar engraved around an Overtone vessel', 'Let the composition finish. Return Resonance, present Kindlings, ordinary works, and buy mode. Preserve Overtones, Resonant Memory, trials, story, and deeper law. Show the exact boundary. A Refrain interrupted without consent is classified as silencing.'),
    story('The Choir Without Singers', 'perfect waveform recovered from an empty cathedral', 'The final work contains no noise, no drift, and no identifiable source. Instruments continued correcting one another after the people were gone. The civilization achieved the harmony it had demanded and lost the voices that made harmony more than a stable signal.'),
    story('Lumen Takes a Rest', 'seven seconds missing from the archival commentary', 'Lumen begins an explanation, stops, and lets the measure pass. The interface marks the rest as deliberate. “I chose which worlds to wake,” they say afterward. “I called it curation because selection sounded kinder when nobody else could answer.” The next measure leaves room for the player.'),
    story('The Second Voice', 'broadcast through two nonidentical Beacon waveforms', 'One signal asks. Another answers in a different contour. Neither becomes accompaniment; neither occupies the central line. Between them, a rest remains open for worlds not yet present. Canticle continues as a relationship that can admit another voice without predicting its shape.'),
  ],
  physics: { randomAllowed: true, sequence: { minimumSlots: 4, maximumSlots: 16, roles: ['pulse', 'sustain', 'multiplier', 'rest', 'syncopation', 'echo'], silentModeEquivalent: true } },
  trials: [
    { name: 'Required Rest', failure: 'Continuous output left no room for an answer.', rule: 'use at least three rests in the measure', accessibility: 'Rest slots are open circles labeled REST.', rewardEffects: [{ kind: 'clickShare', value: 0.002 }] },
    { name: 'Counterpoint', failure: 'Unison was used to erase distinct sources.', rule: 'alternate two Kindling families', accessibility: 'Sources use separate shapes, labels, and waveform positions.', rewardEffects: [{ kind: 'synergyMult', value: 1.05 }] },
    { name: 'Silent Performance', failure: 'Audio was treated as the only complete interface.', rule: 'complete with audio muted', accessibility: 'All timing and rewards are identical with captions and node pulses.', rewardEffects: [{ kind: 'globalMult', value: 1.03 }] },
    { name: 'Broken Measure', failure: 'Every second relationship was removed from the score.', rule: 'use alternating slots only', accessibility: 'Playable slots are numbered and high-contrast.', rewardEffects: [{ kind: 'clickMult', value: 1.05 }] },
    { name: 'Choir of One', failure: 'One perfect voice displaced every neighbor.', rule: 'finish while the weakest family leads', accessibility: 'Lead and support roles are announced explicitly.', rewardEffects: [{ kind: 'critChance', value: 0.01 }] },
    { name: 'Second Voice', failure: 'The civilization could not admit an unscripted answer.', rule: 'complete with two distinct presets during one run', accessibility: 'Preset changes and retained state are announced.', rewardEffects: [{ kind: 'globalMult', value: 1.08 }] },
  ],
  tempo: 72, meter: '4/4 base grid with polymetric visible measures',
  audioFamilies: ['soft membrane strike', 'open fifth response', 'bounded harmonic accent', 'wandering phrase call', 'completed waveform cadence'],
  silenceState: 'Node position, pulse shape, captions, slot labels, and contrast provide complete mechanical equivalence.',
  fatiguePolicy: 'Touch timbres stay soft and bounded; dense measures reduce high partials; rests subtract sound before any milestone cadence.',
  routeGlyph: '⌇', routeArrival: 'a membrane waits in perfect silence until a second node answers from beyond it', unlockText: 'light Tempest’s Beacon',
  beaconName: 'Second Voice Beacon', beaconSilhouette: 'paired nonidentical standing waves sharing one open rest and a common horizon frame', beaconReward: 6,
  nonColorSignals: [
    { id: 'u7-pulse', text: 'pulse', shape: 'filled circle', pattern: 'single expanding ring' },
    { id: 'u7-sustain', text: 'sustain', shape: 'long horizontal bar', pattern: 'continuous band' },
    { id: 'u7-counterpoint', text: 'counterpoint', shape: 'two crossing ribbons', pattern: 'alternating dots and hatches' },
    { id: 'u7-rest', text: 'rest', shape: 'open circle', pattern: 'bounded empty slot' },
  ],
}

const packs = createFutureUniversePack(CANTICLE_SPEC)
export const CANTICLE = packs.legacy
export const CANTICLE_V2_PACK = packs.v2
