import type {
  AudioBusDef,
  AudioBusId,
  AudioCueDef,
  UniverseAudioDef,
} from '../../content/universes/types'

const bus = (
  id: AudioBusId,
  parent: AudioBusId | null,
  defaultGain: number,
): AudioBusDef => ({
  id,
  parent,
  defaultGain,
  userControllable: true,
  muteBehavior: 'suppress-audio-only',
})

export const TIDEFALL_AUDIO_BUSES: readonly AudioBusDef[] = [
  bus('master', null, 0.82),
  bus('music', 'master', 0.58),
  bus('ambient', 'master', 0.45),
  bus('interface', 'master', 0.62),
  bus('touch', 'master', 0.7),
  bus('purchase', 'interface', 0.66),
  bus('omen', 'master', 0.74),
  bus('story', 'master', 0.56),
  bus('ceremony', 'master', 0.78),
]

const cue = (
  id: string,
  cueBus: AudioBusId,
  family: string,
  synthesisKey: string,
  targetPeakDb: number,
  minimumIntervalMs: number,
  priority: AudioCueDef['priority'],
  muteGroup: string,
  mutedFallback: AudioCueDef['mutedFallback'],
): AudioCueDef => ({
  id,
  bus: cueBus,
  family,
  synthesisKey,
  targetPeakDb,
  maximumPeakDb: -6,
  minimumIntervalMs,
  maximumConcurrentInstances: priority === 'normal' ? 2 : 1,
  priority,
  muteGroup,
  mutedFallback,
})

export const TIDEFALL_AUDIO_CUES: readonly AudioCueDef[] = [
  cue(
    'tide-click-pressure',
    'touch',
    'nacre-pressure',
    'tide-pressure-drop-short',
    -16,
    80,
    'normal',
    'tide-touch',
    'none',
  ),
  cue(
    'tide-purchase-rise',
    'purchase',
    'glass-current-interval',
    'tide-purchase-minor-seventh-rise',
    -14,
    120,
    'normal',
    'tide-purchase',
    'visual',
  ),
  cue(
    'tide-critical-crest',
    'touch',
    'pressure-crest-accent',
    'tide-critical-pressure-bloom',
    -12,
    180,
    'important',
    'tide-critical',
    'visual',
  ),
  cue(
    'tide-omen-spring-call',
    'omen',
    'spring-tide-call',
    'tide-omen-rising-glass-call',
    -11,
    500,
    'important',
    'tide-omens',
    'visual-and-caption',
  ),
  cue(
    'tide-omen-undertow-call',
    'omen',
    'undertow-call',
    'tide-omen-reversed-pressure-call',
    -11,
    500,
    'important',
    'tide-omens',
    'visual-and-caption',
  ),
  cue(
    'tide-omen-pearl-call',
    'omen',
    'moon-pearl-call',
    'tide-omen-nacre-chime-call',
    -12,
    500,
    'important',
    'tide-omens',
    'visual-and-caption',
  ),
  cue(
    'tide-omen-bloom-call',
    'omen',
    'abyssal-bloom-call',
    'tide-omen-hadal-flower-call',
    -10,
    500,
    'important',
    'tide-omens',
    'visual-and-caption',
  ),
  cue(
    'tide-omen-leviathan-call',
    'omen',
    'leviathan-migration-call',
    'tide-omen-three-surfacing-call',
    -10,
    900,
    'important',
    'tide-omens',
    'visual-and-caption',
  ),
  cue(
    'tide-undertow-cadence',
    'ceremony',
    'undertow-epoch-cadence',
    'tide-undertow-reverse-envelope-cadence',
    -8,
    2_500,
    'ceremony',
    'tide-ceremony',
    'visual-and-caption',
  ),
  cue(
    'tide-archive-sounding',
    'story',
    'pelagic-record-sounding',
    'tide-archive-pressure-plate-resolve',
    -13,
    500,
    'important',
    'tide-archive',
    'caption',
  ),
  cue(
    'tide-beacon-answer',
    'ceremony',
    'shoreless-lighthouse-answer',
    'tide-beacon-world-current-answer',
    -8,
    2_500,
    'ceremony',
    'tide-beacon',
    'visual-and-caption',
  ),
]

export const TIDEFALL_AUDIO: UniverseAudioDef = {
  tempoBpm: 60,
  meter: '6/8 pressure sway',
  buses: TIDEFALL_AUDIO_BUSES,
  cues: TIDEFALL_AUDIO_CUES,
  clickMaterialCue: 'tide-click-pressure',
  purchaseIntervalCue: 'tide-purchase-rise',
  criticalAccentCue: 'tide-critical-crest',
  omenCallCue: 'tide-omen-spring-call',
  prestigeCadenceCue: 'tide-undertow-cadence',
  stems: [
    {
      id: 'tide-stem-surface',
      kindlingFamily: 'spark',
      bus: 'music',
      description: 'Filtered droplets and a slow pressure pulse for surface Kindlings.',
    },
    {
      id: 'tide-stem-reef',
      kindlingFamily: 'forge',
      bus: 'music',
      description: 'Glass harmonics and kelp-fiber percussion for reef civilization.',
    },
    {
      id: 'tide-stem-pelagic',
      kindlingFamily: 'starseed',
      bus: 'music',
      description: 'Distant migratory synthesis and minor-seventh current swells.',
    },
    {
      id: 'tide-stem-hadal',
      kindlingFamily: 'loom',
      bus: 'music',
      description: 'Sub-bass trench pressure and sparse whale-like harmonic calls.',
    },
  ],
  silenceState: 'Only the Tideclock shape, pressure contours, and captioned crest remain.',
  fatiguePolicy: 'Touch pitch stays below the glass-harmonic band; repeated pressure drops attenuate after four per second, Omens duck touch and ambience, and Undertow begins with subtraction rather than added loudness.',
}
