import { createFutureUniversePack, type FutureUniverseSpec } from '../future-pack'

const kindling = (name: string, flavor: string, silhouette: string) => ({ name, flavor, silhouette })
const archive = (name: string, glyph: string, observation: string, implication: string, effect: string, silhouette: string) => ({ name, glyph, observation, implication, effect, silhouette })
const story = (title: string, provenance: string, text: string) => ({ title, provenance, text })

export const VISHNULOK_STRAIN_COPY = [
  { id: 'thinning-coast', name: 'Thinning Coast', glyph: '⌇', description: 'A coast thins where a long sustaining route has fallen quiet.', preference: 'long route (6+ shelters), sheltered burden', silhouette: 'broken shore arc beside six numbered shelter marks', pattern: 'wide-spaced shore hatching', restoredFeature: 'repaired reef seam' },
  { id: 'scattered-school', name: 'Scattered School', glyph: '∴', description: 'A returning school has scattered across the open water.', preference: 'short route, far-reaching burden', silhouette: 'three separated school marks around one short return line', pattern: 'three dotted groups', restoredFeature: 'returning ferry line' },
  { id: 'crowded-shelter', name: 'Crowded Shelter', glyph: '⌂', description: 'One shelter is carrying more relation than its threshold can hold.', preference: 'medium route, strained burden', silhouette: 'open arch crossed by three measured threshold bars', pattern: 'dense ruled center', restoredFeature: 'lit harbor lamp' },
  { id: 'divided-currents', name: 'Divided Currents', glyph: '≍', description: 'Two sustaining currents are running too far apart to exchange warmth.', preference: 'Ocean Balance circuit at any length', silhouette: 'two parallel currents joined by one open return', pattern: 'paired lines with a single bridge', restoredFeature: 'joined current marker' },
] as const

export const VISHNULOK_STRAIN_LUMEN = {
  firstStrain: 'The ocean did not ask us to defeat anything. It made one strained relation visible and waited for a route that could come home.',
  firstAnswer: 'The correction returned what it carried. A gold thread remains on the chart, but the refuge is still open.',
} as const

/** Canonical Vishnulok economy, presentation, and content identity. */
export const VISHNULOK_SPEC: FutureUniverseSpec = {
  id: 'vishnulok',
  prefix: 'vishnulok',
  name: 'Vishnulok',
  shortName: 'Vishnulok',
  epithet: 'The Sustaining Ocean',
  premise: 'Enter a realm where preservation means noticing imbalance, offering refuge, and returning every correction to the living whole.',
  primaryVerb: 'sustain',
  question: 'Can order remain responsive enough to protect life without imprisoning it?',
  currency: 'Continuity',
  currencyGlyph: '≈',
  currencyMaterial: 'shared duration carried through currents, shelters, seasons, and remembered routes',
  heartName: 'The Endless Circuit',
  heartPhenomenon: 'A calm current-map that gathers strain, declares a restorative path, and returns what it carries without impact.',
  heartSilhouette: 'three ocean currents looping around an open refuge with one gold return line',
  heartVerb: 'receives a burden, traces its correction, and returns to still water',
  achievementPower: 'Steadiness',
  epochName: 'Renewal',
  epochMatter: 'Returns',
  epochMatterSingular: 'Return',
  epochGlyph: '↶',
  epochMaterial: 'preserved knowledge of where continuity bent, repaired, sheltered, and rejoined the whole',
  archiveName: 'Ocean of Continuance',
  archiveGlyph: '≋',
  archiveRecord: 'THE MAP THAT COMES HOME — LAST SOUNDING\n\nPreservation is not a wall around yesterday. A shore survives by changing with water. A shelter survives by opening. A route survives by returning what it carries.\n\nThe current closes without becoming a cage. The ocean grows still without becoming lifeless.\n\n— entered by the keepers of the unclaimed harbor',
  palette: { accentHue: 218, bg: '#050916', accent: '#5577c8', gold: '#f5e5ae', panel: 'rgba(8, 14, 35, 0.9)' },
  visualMaterials: ['indigo water', 'milk-white foam', 'weathered harbor stone', 'lotus-leaf green', 'hammered gold current', 'pearl shell', 'moonlit salt'],
  primarySilhouettes: ['a calm ocean crossed by one declared returning current', 'three broad sheltering loops around an unoccupied refuge', 'a horizon-scale circuit that closes without enclosing the sea'],
  economy: {
    baseCosts: [15, 166, 2_288, 22_880, 358_400, 5_120_000, 55_080_000, 884_000_000, 9_000_000_000, 38_000_000_000, 1_700_000_000_000, 14_000_000_000_000, 120_000_000_000_000, 1_000_000_000_000_000, 8_500_000_000_000_000, 73_000_000_000_000_000, 630_000_000_000_000_000, 500_000_000_000_000_000_000],
    baseRates: [0.336, 2.565, 25.3, 276.75, 1_837.5, 22_785, 178_350, 1_236_000, 16_280_000, 118_400_000, 1_281_250_000, 9_275_000_000, 101_250_000_000, 974_100_000_000, 7_360_000_000_000, 77_000_000_000_000, 740_250_000_000_000, 7_790_000_000_000_000],
    costMultiplier: 1.16,
  },
  signatureUpgrades: (generators) => [
    { id: 'vishnulok-capacitive-rain', name: 'Reciprocal Current', flavor: 'What one shelter receives, another route learns to carry.', cost: 3e7, glyph: '≋', hue: 218, unlock: { gen: generators[4].id, count: 10 }, effects: [{ kind: 'synergy', gen: generators[4].id, per: generators[1].id, value: 0.018 }] },
    { id: 'vishnulok-declared-grounding', name: 'Declared Correction', flavor: 'A restorative path is named before its power is welcomed.', cost: 9e10, glyph: '↶', hue: 172, unlock: { clicks: 1_200 }, effects: [{ kind: 'clickShare', value: 0.018 }, { kind: 'critMult', value: 1.5 }] },
    { id: 'vishnulok-auroral-return', name: 'Horizon Return', flavor: 'The completed circuit gives its strength back to the whole ocean.', cost: 6e16, glyph: '⌒', hue: 42, unlock: { gen: generators[15].id, count: 10 }, effects: [{ kind: 'globalMult', value: 1.7 }, { kind: 'critChance', value: 0.03 }] },
  ],
  kindlings: [
    kindling('Still Drop', 'One measure of continuity waits without being mistaken for inertia.', 'single drop held between two open current marks'),
    kindling('Tidal Thread', 'A narrow current remembers how to leave and how to return.', 'blue thread looping through two gold shore pins'),
    kindling('Bearing Current', 'A route accepts weight only after naming where it will set that weight down.', 'broad current band carrying three visible load marks'),
    kindling('Shelter Reef', 'Protection grows porous enough for the lives it serves to pass through.', 'low reef arch with many unequal refuge openings'),
    kindling('Returning School', 'Many small lives coordinate without surrendering their separate motion.', 'fish-like marks turning together around an open center'),
    kindling('Moonwake Garden', 'A floating garden bends with the tide and repairs the water beneath it.', 'lotus-leaf platforms joined by a pale wake'),
    kindling('Confluence Gate', 'Two histories meet without requiring either current to disappear.', 'paired rivers entering one wide, unbarred estuary'),
    kindling('Restoring Shoal', 'Damage becomes a shared route for repair instead of a private debt.', 'stepped shoal carrying alternating broken and mended stones'),
    kindling('Balance Estuary', 'Fresh and salt water negotiate a living boundary every hour.', 'interleaved light and dark currents around reed banks'),
    kindling('Horizon Keeper', 'A distant marker keeps departure and return mutually legible.', 'low beacon arch crossed by one returning horizon line'),
    kindling('Season Wheel', 'Change repeats without demanding that any season become permanent.', 'four unequal seasonal arcs around an empty hub'),
    kindling('Deepwater Library', 'The oldest routes remain readable under pressure and revision.', 'shelf-like terraces descending through indigo water'),
    kindling('World Current', 'Every local repair enters a circulation larger than its first purpose.', 'planetary ocean bands joined by one gold correction path'),
    kindling('Refuge Archipelago', 'Safety is distributed so no single shore can own it.', 'many islands linked by open ferry curves'),
    kindling('Cosmic Ocean', 'Distance itself becomes a sustaining medium rather than an empty gap.', 'wide indigo field with milk-white boundary waves'),
    kindling('Order Meridian', 'A measure of balance stays useful because it can move when life moves.', 'gold meridian bending around three changing coastlines'),
    kindling('The Endless Circuit', 'Correction travels outward, returns, and leaves the refuge open.', 'three broad loops closing around an unoccupied harbor'),
    kindling('The Still Horizon', 'Completion arrives as calm circulation, not frozen perfection.', 'long quiet horizon with one final line returning beneath it'),
  ],
  archives: [
    archive('Saltless Pearl', '◉', 'A pearl formed in water that records no salinity and every tide.', 'The keepers valued what could cross boundaries without denying them.', 'improves continuity gathered at the start of a circuit', 'pale pearl crossed by four tide contours'),
    archive('Returning Tide Map', '↶', 'Every outgoing line has a separately labeled homeward curve.', 'A route was incomplete until its aftermath rejoined public life.', 'forecasts when the selected circuit can close', 'paired departure and return paths around a shore'),
    archive('Refuge Threshold', '⌂', 'A harbor gate measures need, never identity or ownership.', 'Its oldest rule says that protection begins before proof.', 'strengthens sheltering circuit conditions', 'open arch above three different vessel marks'),
    archive('Unbroken Reed Boat', '⌣', 'Its hull flexes through pressure that shattered the rigid fleet.', 'Endurance came from responsive structure, not invulnerability.', 'improves long restorative routes', 'curved reed hull with visible woven joins'),
    archive('Twin Current Chart', '≋', 'Two opposing streams exchange warmth without merging.', 'Balance was maintained as relationship rather than sameness.', 'repeats part of the previous completed return', 'two counterflow lines joined by small transfer bars'),
    archive('Night Watch Lamp', '◇', 'A low harbor light remains visible without commanding the sea.', 'Care continued during calm periods when urgency offered no reward.', 'labels circuits that need attention', 'shielded lamp reflected in three still ripples'),
    archive('Seasonal Ledger', '◫', 'The same shore is drawn four times and called accurate each time.', 'The archive records stability as bounded change.', 'accelerates responsive correction', 'four offset coast maps around one date ring'),
    archive('Coral Repair Stone', '✣', 'New growth follows a fracture without hiding where the break occurred.', 'Repair remained accountable to damage and to the lives displaced by it.', 'extends the useful duration of a completed return', 'broken stone joined by branching coral seams'),
    archive('Horizon Knot', '⌁', 'A navigation knot encodes departure, burden, refuge, and return.', 'No segment is called victory; the route ends at restored relation.', 'improves circuit circulation', 'four-loop knot with one open crossing'),
    archive('Four-Shore Agreement', '□', 'Four harbors share capacity and publish every transfer.', 'Order survives because no shore can privatize the whole circuit.', 'unlocks saved correction thresholds', 'four shore marks joined by a rounded square current'),
    archive('Still Ocean Sounding', '·', 'The depth line records movement beneath a surface that appears motionless.', 'Calm was treated as a living condition requiring attention.', 'adds exact reserve and return forecasts', 'vertical sounding line through five quiet layers'),
    archive('The Map That Comes Home', '∞', 'Its final line rejoins the first without enclosing the page.', 'Vishnulok offers preservation as continual return, refuge, and repair.', 'completes Continuance and reveals the Still Horizon', 'open circuit crossing an ocean horizon and returning below it'),
  ],
  shelfNames: ['Refuge', 'Correction', 'Return'],
  shelfRewards: ['Shelters gather continuity without closing their thresholds.', 'Declared circuits restore imbalance with visible limits.', 'Completed returns preserve route knowledge through every Renewal.'],
  omens: [
    { name: 'Gentle Return', description: 'A prior correction comes home carrying a bounded share of what it restored.', silhouette: 'pale current retracing an open gold route', motion: 'tidal', effects: [{ kind: 'clickShare', value: 0.008 }] },
    { name: 'Refuge Opens', description: 'A temporary harbor strengthens work that protects the whole field.', silhouette: 'wide stone arch opening over calm water', motion: 'still', effects: [{ kind: 'globalMult', value: 1.15 }] },
    { name: 'Course Correction', description: 'Three visible markers bend one route away from accumulating harm.', silhouette: 'gold path curving through three numbered current gates', motion: 'tidal', effects: [{ kind: 'critChance', value: 0.025 }] },
    { name: 'Still Water', description: 'A calm interval banks continuity and makes a hidden relation legible.', silhouette: 'unbroken horizon with a single deep sounding line', motion: 'still', effects: [{ kind: 'globalMult', value: 1.1 }, { kind: 'clickMult', value: 1.1 }] },
  ],
  doctrines: [
    { name: 'Daily Return', description: 'Favor frequent, modest corrections whose aftermath rejoins the whole.', favoredMotivations: ['performer', 'optimizer'], visualSignature: 'short returning current with one visible handoff', effects: [{ kind: 'clickShare', value: 0.008 }] },
    { name: 'Refuge Circuit', description: 'Carry a large burden through many shelters before completing the return.', favoredMotivations: ['performer', 'wayfinder'], visualSignature: 'long loop touching seven open harbors', effects: [{ kind: 'globalMult', value: 1.16 }] },
    { name: 'Measured Correction', description: 'Favor stable circulation, offline gain, and a declared middle path.', favoredMotivations: ['restorer', 'optimizer'], visualSignature: 'broad current crossing measured coastlines and returning', effects: [{ kind: 'globalMult', value: 1.1 }, { kind: 'synergyMult', value: 1.08 }] },
    { name: 'Ocean Balance', description: 'Favor active openings, visible thresholds, and responsive rerouting.', favoredMotivations: ['performer', 'archivist'], visualSignature: 'four unequal currents held in one changing balance field', effects: [{ kind: 'clickMult', value: 1.25 }, { kind: 'critChance', value: 0.02 }] },
  ],
  lumen: {
    awake: 'The ocean is calm because every current knows where it may return. Nothing here is asleep.',
    first: 'A Still Drop can endure without refusing change. That little reed boat has passed us twice now—outward, homeward, outward again. It has the better map.',
    law: 'Choose the circuit, its reach, and the burden it can safely carry. A correction is complete only when it comes home.',
    civil: 'The Refuge Archipelago distributes safety. No central harbor can turn welcome into ownership.',
    archive: 'The Ocean of Continuance keeps routes and repairs, including the harms that made repair necessary.',
    omen: 'That current did not reward force. It noticed a strained relation and returned after easing it.',
    epoch: 'Renewal preserved the completed circuit as a Return, then let the water choose new shores.',
    cosmic: 'The Cosmic Ocean sustains distance itself. Empty space was another careless name I inherited.',
    question: 'If order cannot respond to suffering, what exactly is it preserving?',
    beacon: 'The Still Horizon is not frozen. Every route continues beneath it, quiet enough to hear the next need.',
  },
  story: [
    story('The Ocean Was Already Whole', 'entered on the first harbor wall', 'Brahmalok opened a passage into a realm that does not wait to be repaired. Vishnulok is alive with currents, shelters, seasons, and continuous acts of care. The Wayfinder is permitted to participate only after accepting that preservation is not ownership of the preserved.'),
    story('A Route Must Return', 'drawn in gold across an indigo tide chart', 'Each correction begins by naming a burden, a reach, and the conditions of refuge. Power that travels outward without returning its effects is not restoration here. The circuit closes only when the altered relation can sustain itself without the instrument.'),
    story('The Open Harbor', 'a threshold covenant copied in many hands', 'Anyone may enter before explaining their need. The harbor records capacity, never worthiness. Its walls break the largest waves and leave many passages for smaller lives. Protection is treated as a temporary relation that must never become a permanent claim.'),
    story('Lakshmi at the Threshold', 'heard in the quiet after the Refuge shelf opens', 'The keepers speak of Lakshmi as an independent sacred presence associated with well-being, fortune, abundance, and flourishing—not a reward multiplier, treasury, collectible, or possession. No portrait appears. The harbor opens, lamps are tended, and Lumen listens without translating presence into inventory.'),
    story('The Endless Support', 'a cosmological note kept outside the instrument diagrams', 'The keepers speak of Ananta as a sacred presence in traditions of the sustaining cosmic ocean, never as machinery, terrain, enemy, or the body of the player’s circuit. The visible loops are ordinary current maps. Their resemblance remains a boundary for reverence, not a license to instrumentalize.'),
    story('The Correction Wheel', 'marginal notes beside a rotating season chart', 'The realm acknowledges the chakra as a sacred attribute of Vishnu and does not place it in the player’s hands. The instrument uses an abstract seasonal wheel with no weapon imagery. It represents timely correction only through measured routes, disclosed limits, and a complete return.'),
    story('Renewal Procedure', 'written beneath the Map That Comes Home', 'Release current Continuity, Kindlings, ordinary works, and buy mode. Preserve the circuit’s relation as one Return. Retain Archives, Echoes, deeper laws, and every freely chosen route. Preview the loss. Require consent. A renewal that cannot name what it disrupts is only erasure.'),
    story('Responsive Order', 'four editions of one coastal law', 'The law changes after a migration, a drought, a new shelter, and a shore collapse. Each edition preserves the purpose of refuge while revising the structure that failed living people. The keepers call this continuity. Clockwork would once have called it contradiction.'),
    story('Lumen Revises Safekeeping', 'annotation beside the Coral Repair Stone', 'Lumen replaces protected object with relation under care and permanent solution with current obligation. “I made systems that survived their people,” they write. “Then I praised the systems for surviving.” The final line is smaller: “Please do not let me call endurance innocent again.”'),
    story('The Still Horizon', 'the last sounding after the circuit closes', 'The ocean settles without becoming empty. Vishnu and Lakshmi remain sacred presences beyond command or depiction; the game offers no audience, favor, weapon, or reward. The completed route returns to the whole. Ahead, a mountain holds stillness of another kind.'),
  ],
  physics: { randomAllowed: true, charge: { minimumPathLength: 1, maximumPathLength: 8, overflowBehavior: 'hold', automationUsesSavedPaths: true } },
  trials: [
    { name: 'Nearest Harbor', failure: 'The shortest correction ignored the relations beyond its first shore.', rule: 'use only Daily Return circuits', accessibility: 'Reserve, threshold, reach, and burden are announced as text.', rewardEffects: [{ kind: 'clickShare', value: 0.002 }] },
    { name: 'Held Continuity', failure: 'Preservation became an excuse to defer necessary change.', rule: 'reach ninety percent reserve before every return', accessibility: 'Reserve includes a percentage and ten labeled segments.', rewardEffects: [{ kind: 'globalMult', value: 1.03 }] },
    { name: 'Broken Passage', failure: 'One closed shelter forced the route to become responsive.', rule: 'complete returns with alternating Kindling tiers', accessibility: 'Available shelters carry numbered shape markers.', rewardEffects: [{ kind: 'critChance', value: 0.01 }] },
    { name: 'Still Surface', failure: 'Calm concealed a strained relation beneath the horizon.', rule: 'complete without active Omens', accessibility: 'Stillness uses an open horizon and explicit status text.', rewardEffects: [{ kind: 'clickMult', value: 1.05 }] },
    { name: 'Three Corrections', failure: 'Repeated intervention replaced a better sustaining relation.', rule: 'reach the target in at most three completed returns', accessibility: 'Remaining return count is persistently announced.', rewardEffects: [{ kind: 'critMult', value: 1.25 }] },
    { name: 'Continuance', failure: 'Repair was celebrated while its evidence was allowed to vanish.', rule: 'finish with all three Ocean of Continuance shelves complete', accessibility: 'Shelf completion uses names, fractions, and distinct icons.', rewardEffects: [{ kind: 'globalMult', value: 1.08 }] },
  ],
  tempo: 72,
  meter: 'slow four-part tide of burden, refuge, correction, and return; no devotional melody is imitated',
  audioFamilies: ['low water contact and shell-like breath', 'warm current interval', 'harbor-stone and water response', 'distant open-water call', 'returning current cadence ending in quiet'],
  silenceState: 'Reserve percentages, segmented and numbered routes, burden and strain labels, return countdowns, confluence state, and captions carry every mechanical signal.',
  fatiguePolicy: 'Water and low material transients soften above four inputs per second; no mantra, raga, conch ceremony, temple bell, or sacred instrument performance is simulated.',
  routeGlyph: '∞',
  routeArrival: 'an indigo ocean opens one gold returning current around an unoccupied refuge; no sacred figure or attribute is offered for use',
  unlockText: 'complete Brahmalok’s Open Lotus passage',
  beaconName: 'Still Horizon Seal',
  beaconSilhouette: 'calm cosmic-ocean horizon crossed by one complete gold return beneath an open refuge',
  beaconReward: 5,
  nonColorSignals: [
    { id: 'vishnulok-building', text: 'continuity gathering', shape: 'open segmented current', pattern: 'ascending numbered tide marks' },
    { id: 'vishnulok-ready', text: 'correction ready', shape: 'closed return line with open harbor', pattern: 'bold threshold mark' },
    { id: 'vishnulok-discharging', text: 'return in progress', shape: 'gold path crossing selected shelters', pattern: 'numbered route sequence' },
    { id: 'vishnulok-calm', text: 'still water', shape: 'unbroken horizon over moving depth line', pattern: 'one deep sounding mark' },
    { id: 'vishnulok-strain', text: 'ocean strain present', shape: 'labeled middle-water marker', pattern: 'strain-specific hatch beside its preferred route' },
    { id: 'vishnulok-strain-answered', text: 'matching correction ready', shape: 'open marker joined to a numbered return', pattern: 'one bridge line through the strain mark' },
    { id: 'vishnulok-confluence', text: 'two returns in confluence', shape: 'paired return lines', pattern: 'two numbered paths overlapping without merging' },
  ],
}

const packs = createFutureUniversePack(VISHNULOK_SPEC)
export const VISHNULOK = packs.legacy
export const VISHNULOK_V2_PACK = packs.v2
