import { createFutureUniversePack, type FutureUniverseSpec } from '../future-pack'

const kindling = (name: string, flavor: string, silhouette: string) => ({ name, flavor, silhouette })
const archive = (name: string, glyph: string, observation: string, implication: string, effect: string, silhouette: string) => ({ name, glyph, observation, implication, effect, silhouette })
const story = (title: string, provenance: string, text: string) => ({ title, provenance, text })

export const PRISMATA_SPEC: FutureUniverseSpec = {
  id: 'prismata',
  prefix: 'u5',
  name: 'Prismata',
  shortName: 'Prismata',
  epithet: 'The Broken Spectrum',
  premise: 'Reassemble a universe whose white light shattered into incompatible colors, geometries, and isolated truths.',
  primaryVerb: 'focus',
  question: 'Does unity require every difference to disappear?',
  currency: 'Chroma',
  currencyGlyph: '◈',
  currencyMaterial: 'labeled wavelength energy carried through crystal and thin-film paths',
  heartName: 'White Lens',
  heartPhenomenon: 'A many-element lens whose empty center remembers the white light every band once shared.',
  heartSilhouette: 'asymmetric triplet lens around a hexagonal white aperture with six labeled wavelength notches',
  heartVerb: 'narrows into a caustic and separates into patterned wavelength paths',
  achievementPower: 'Clarity',
  epochName: 'Refraction',
  epochMatter: 'Facets',
  epochMatterSingular: 'Facet',
  epochGlyph: '◇',
  epochMaterial: 'crystallized optical relationships that preserve a solved spectrum',
  archiveName: 'Spectrum Vault',
  archiveGlyph: '⬡',
  archiveRecord: 'WHITE-LIGHT RELIQUARY — FINAL CALIBRATION\n\nWe divided the spectrum so no band could dominate another. The red cities kept warmth; the violet cities kept memory; the invisible cities kept what none of us wished to see.\n\nIsolation prevented conquest and ended the shared sky. Reconstruct white without erasing the labels. Difference is not noise.\n\n— last curator of the Spectrum Vault',
  palette: { accentHue: 286, bg: '#070812', accent: '#a68cff', gold: '#f4edff', panel: 'rgba(14, 14, 32, 0.88)' },
  visualMaterials: ['crystal lattice', 'optical glass', 'thin-film interference', 'polarizing membrane', 'fluorescent mineral', 'fiber light', 'diffraction foil'],
  primarySilhouettes: ['a labeled optical bench with three source bands', 'an interlocked lens lattice joining six distinct paths', 'a white horizon whose component bands remain visible'],
  economy: {
    costScales: [0.85, 0.9, 0.95, 1, 1.08, 1.16, 1.25, 1.35, 1.5, 1.65, 1.8, 2, 2.2, 2.45, 2.75, 3.1, 3.5, 4],
    rateScales: [0.9, 1.05, 1.2, 0.95, 1.25, 1.35, 1.1, 1.45, 1.2, 1.55, 1.35, 1.75, 1.5, 1.9, 1.65, 2.1, 1.8, 2.4],
    costMultiplier: 1.145,
  },
  signatureUpgrades: (generators) => [
    { id: 'u5-complementary-pairs', name: 'Complementary Pairs', flavor: 'Distant bands become evidence for one another.', cost: 2e7, glyph: '⋈', hue: 286, unlock: { gen: generators[5].id, count: 10 }, effects: [{ kind: 'synergy', gen: generators[5].id, per: generators[0].id, value: 0.015 }] },
    { id: 'u5-fluorescent-memory', name: 'Fluorescent Memory', flavor: 'Delayed light returns carrying the path it traveled.', cost: 5e10, glyph: '◫', hue: 312, unlock: { gen: generators[7].id, count: 25 }, effects: [{ kind: 'globalMult', value: 1.35 }] },
    { id: 'u5-labeled-white', name: 'Labeled White', flavor: 'Synthesis keeps every contributing name at the rim.', cost: 3e16, glyph: '✧', hue: 252, unlock: { gen: generators[15].id, count: 10 }, effects: [{ kind: 'globalMult', value: 1.6 }, { kind: 'synergyMult', value: 1.25 }] },
  ],
  kindlings: [
    kindling('Photon Seed', 'One packet of possibility waits for a direction.', 'single diamond photon inside a short dashed ray'),
    kindling('Red Ember Ray', 'Warmth travels first, carrying Emberlight without copying it.', 'broad ray with three heat-wave notches'),
    kindling('Amber Band', 'A middle wavelength learns to bridge rather than blend.', 'striped amber ribbon through a triangular aperture'),
    kindling('Green Line', 'A narrow spectral line makes living structure measurable.', 'thin line crossing a leaf-shaped diffraction slit'),
    kindling('Blue Wake', 'A fast band leaves geometry behind it like a remembered shore.', 'double blue caustic with a chevron wake'),
    kindling('Violet Spark', 'The shortest visible band writes at the edge of perception.', 'six-point spark inside a dotted ultraviolet fringe'),
    kindling('Prism', 'Separation becomes an instrument instead of a wound.', 'scalene prism with three labeled exit paths'),
    kindling('Fluorescent Garden', 'Stored light returns later in a different, declared color.', 'four mineral blooms beneath one delayed glow arc'),
    kindling('Polarizer', 'Orientation becomes a choice the interface can name without color.', 'crossed membrane frame with directional hatch marks'),
    kindling('Lens Foundry', 'Curvature is manufactured with tolerances and consequences.', 'three nested grinding wheels framing a lens blank'),
    kindling('Diffraction Choir', 'Many slits disagree in phase and produce one legible pattern.', 'grating comb projecting five unequal maxima'),
    kindling('Spectrum Bridge', 'Separated bands cross without surrendering their labels.', 'six parallel fibers braided through open bridge piers'),
    kindling('Crystal Observatory', 'The sky is inspected through geometry it can answer.', 'faceted dome with offset meridian lens'),
    kindling('Aurora Engine', 'Charged light writes broad curtains across the far field.', 'three folded auroral ribbons around a magnetic spindle'),
    kindling('Lattice Moon', 'A world-scale crystal holds fractures as useful boundaries.', 'crescent lattice moon with hexagonal fault cells'),
    kindling('Rainbow Horizon', 'Every visible family arrives at the same distance by a different path.', 'layered horizon arc with six pattern bands'),
    kindling('The Invisible Band', 'What cannot be seen still receives a number, shape, and place.', 'dark central ribbon bordered by infrared bars and ultraviolet dots'),
    kindling('The White Star', 'Unity returns as relationship, not disappearance.', 'white six-rayed star with every component band separated at its rim'),
  ],
  archives: [
    archive('Newton’s Lost Prism', '△', 'A prism with one face ground for a color the eye cannot name.', 'Its spectrum contains signatures from every restored world, separated but mutually legible.', 'unlocks the first complementary-pair recipe', 'wedge prism with seven exit notches'),
    archive('Black Diamond Lattice', '⬡', 'A crystal that transmits nothing and maps every absorbed path.', 'The missing light outlines a city built inside the lattice defects.', 'strengthens narrow-band coherence', 'black hexagonal lattice with one bright vacancy'),
    archive('Fluorescent Fossil', '◫', 'A mineral remembers daylight centuries after burial.', 'Its delayed glow is a message paced for a civilization that expected interruption.', 'increases delayed-light storage', 'ribbed fossil emitting an offset second contour'),
    archive('Polarized Moon Shard', '◒', 'The shard brightens only when its hatch marks align with the White Lens.', 'It belonged to Tidefall’s absent moon before anyone removed it.', 'adds orientation labels to optical Omens', 'crescent shard crossed by parallel hatch marks'),
    archive('Infrared Garden', '▥', 'Warm flowers bloom beyond visible red.', 'Their petals turn toward occupied rooms rather than stars.', 'improves offline fluorescence', 'four thermal petal outlines around a square core'),
    archive('Ultraviolet Script', '⌁', 'A text appears only after the page has stopped being watched.', 'The script names Prismata’s isolated factions as parts of one sentence.', 'reveals hidden absorption records', 'zigzag script beneath dotted ultraviolet bars'),
    archive('Gravitational Lens Chip', '◉', 'A glass sliver bends not light but the route between universes.', 'Its caustic points simultaneously toward Emberlight and the Garden.', 'strengthens cross-band recipes', 'offset lens ring with a four-image cross'),
    archive('Frozen Rainbow', '⌒', 'Six bands stand still inside clear ice without mixing.', 'The ice was made when Prismata stopped every negotiation between colors.', 'preserves recipe state through Refraction', 'layered arc trapped inside a fractured rectangle'),
    archive('Absorption Crown', '♢', 'A crown defined entirely by the lines it removes.', 'Each dark line names a cost the old rulers refused to share.', 'turns missing bands into bounded bonuses', 'open crown of five dark spectral gaps'),
    archive('Fiber Star Map', '※', 'Every star is connected by a labeled optical fiber.', 'The map depicts distance as transmission loss rather than emptiness.', 'improves saved lens loadouts', 'knotted fiber web around four star junctions'),
    archive('Colorless Butterfly', '⋈', 'Its wings differ by interference pattern, never hue.', 'The species survived the division because it had never treated color as identity.', 'adds pattern-first accessibility rewards', 'paired wings with dots on one side and bars on the other'),
    archive('White-Light Reliquary', '✧', 'A white source whose six ingredients remain visible at the edge.', 'Unity was possible all along; only forced sameness made it dangerous.', 'completes Reunion and reveals the Beacon route', 'white aperture surrounded by six separated facet petals'),
  ],
  shelfNames: ['Separation', 'Transmission', 'Reunion'],
  shelfRewards: ['Focused bands gain stable production without suppressing other labels.', 'Saved lens paths improve click and Archive interaction.', 'White synthesis gains a capstone bonus while every component remains inspectable.'],
  omens: [
    { name: 'Caustic Flare', description: 'A bright path crosses the bench; aligned lenses multiply its bounded reward.', silhouette: 'curved caustic blade crossing three lens stations', motion: 'optical', effects: [{ kind: 'clickMult', value: 1.25 }] },
    { name: 'Dark Line', description: 'One band is briefly removed, exposing an absorption record and alternate recipe.', silhouette: 'spectral ribbon interrupted by one labeled black notch', motion: 'optical', effects: [{ kind: 'globalMult', value: 1.12 }] },
    { name: 'Polar Aurora', description: 'Match its orientation using shape and hatch cues as well as color.', silhouette: 'folded curtain with rotating parallel hatch pattern', motion: 'optical', effects: [{ kind: 'critChance', value: 0.02 }] },
    { name: 'Cherenkov Wake', description: 'A rare blue trace chains through the correct declared lens order.', silhouette: 'sharp conical wake passing four numbered apertures', motion: 'optical', effects: [{ kind: 'clickShare', value: 0.01 }] },
  ],
  doctrines: [
    { name: 'Coherence', description: 'Concentrate one narrow wavelength for focused output and stronger touch.', favoredMotivations: ['optimizer', 'performer'], visualSignature: 'one thick labeled ray passing a long aperture train', effects: [{ kind: 'clickMult', value: 1.35 }] },
    { name: 'Synthesis', description: 'Balance every band into stable white-light production.', favoredMotivations: ['restorer', 'optimizer'], visualSignature: 'six patterned paths meeting without losing their borders', effects: [{ kind: 'globalMult', value: 1.14 }] },
    { name: 'Fluorescence', description: 'Store delayed and offline energy for a later afterglow.', favoredMotivations: ['restorer', 'archivist'], visualSignature: 'a mineral garden with offset before-and-after contours', effects: [{ kind: 'globalMult', value: 1.08 }, { kind: 'critChance', value: 0.01 }] },
    { name: 'Diffraction', description: 'Spread bands into active Omens, broad effects, and Archive discovery.', favoredMotivations: ['performer', 'archivist'], visualSignature: 'a grating fan with unequal numbered maxima', effects: [{ kind: 'clickShare', value: 0.01 }] },
  ],
  lumen: {
    awake: 'The White Lens did not make one color. It made room for six answers.',
    first: 'A Photon Seed has no assigned wavelength until you route it. Prismata begins with permission, not destiny.',
    law: 'Move a Kindling between bands and the recipe changes its argument. The labels are part of the machinery.',
    civil: 'A Fluorescent Garden stores light the visible cities discarded. Someone planned for a future observer.',
    archive: 'The Spectrum Vault records what passed through, what was absorbed, and who was omitted from the measurement.',
    omen: 'That caustic crossed three paths and belonged to none of them. Shared light can still have provenance.',
    epoch: 'Refraction did not preserve a color. It preserved the solved relationship between colors as a Facet.',
    cosmic: 'The Aurora Engine writes with charged light across every border the old cities drew around the sky.',
    question: 'If white can keep every band legible, what were they protecting when they chose isolation?',
    beacon: 'The White Star answers as one signal with six names. Unity survived the labels.',
  },
  story: [
    story('The First Separation', 'etched on the rear face of the Photon Seed', 'White light entered the first prism and left as neighbors. The record does not describe this as damage. Each band gained a name, a number, and a shape, then turned back toward the others to compare what it had seen. Division was once a method of understanding.'),
    story('Six Municipal Spectra', 'a charter printed in wavelength order and repeated in patterns', 'The early cities assigned public work by band: warmth, growth, navigation, memory, communication, and the invisible maintenance none wished to acknowledge. Every ordinance appears twice, once in color and once in hatch marks. Accessibility was ordinary civic grammar before separation became ideology.'),
    story('The Optical Bench', 'calibration notes beneath the White Lens', 'Lens changes cost nothing because the builders expected argument. A recipe could be focused, balanced, delayed, or spread, then replaced without punishment. The note warns that a free reconfiguration is not indecision; it is how a shared instrument remains answerable to more than one observer.'),
    story('A Garden Under Infrared', 'thermal plate recovered from an abandoned greenhouse', 'The gardeners worked in wavelengths most citizens could not perceive. They labeled every bed with raised patterns so visitors would know that unseen did not mean absent. When the visible factions closed their borders, the garden continued sending heat through the walls until nobody remained to receive it.'),
    story('Minutes of the White Council', 'six transparent sheets readable only when overlaid', 'Every faction feared that synthesis would erase its distinct truth. The council proposed a white output whose component paths stayed separately inspectable. The motion failed by one vote. On the final sheet, the dissenter has written: I mistook being visible for being alone.'),
    story('The Black Diamond District', 'absorption map translated into street geometry', 'Nothing escaped the district, so outsiders called it secretive. Inside, absorption was public infrastructure: stored heat, sheltered archives, rooms where brightness could not demand attention. The district vanished from the shared census because the census measured only transmitted light.'),
    story('Refraction Procedure', 'a Facet mold beside the Epoch chamber', 'Split the current spectrum. Preserve the solved relationship as one Facet. Return Chroma, Kindlings, ordinary refinements, and buy mode to their opening states. Retain Archives, Echoes, deeper laws, and every declared recipe. Preview the loss. Refraction without consent is classified as shattering.'),
    story('The Shared Sky Goes Dark', 'astronomical mosaic with six non-overlapping horizons', 'No faction attacked another. Each simply filtered the sky until only its own evidence remained. Navigation failed first, then climate exchange, then language. The Devourer passed between the isolated beams because no detector could assemble a complete image of it.'),
    story('Lumen in Grayscale', 'an annotation added after the Spectrum Vault opened', 'Lumen disables color and studies the world through pattern, wavelength number, and geometry. Nothing mechanical disappears. “That should not feel like a revelation,” they write. “It should feel like a minimum.” The next line is quieter: “I once catalogued people as though one description could contain them.”'),
    story('White Without Silence', 'broadcast from the completed White Star', 'Six paths enter. One white signal leaves. At the rim, every band remains separately labeled and none is asked to dim. The Beacon repeats the old council motion with one amendment: unity is a relationship maintained by difference, not the place difference goes to die.'),
  ],
  physics: {
    randomAllowed: true,
    spectrum: {
      bandIds: ['u5-red', 'u5-amber', 'u5-green', 'u5-blue', 'u5-violet', 'u5-invisible'],
      recipeIds: ['coherence', 'synthesis', 'fluorescence', 'diffraction'],
      freeReconfiguration: true,
      nonColorLabelsRequired: true,
    },
  },
  trials: [
    { name: 'Missing Red', failure: 'Warmth was treated as ownership rather than a shared condition.', rule: 'synthesize without the red family', accessibility: 'Red is identified by broad bars and the number 650, never by hue alone.', rewardEffects: [{ kind: 'clickMult', value: 1.05 }] },
    { name: 'Narrow Truth', failure: 'One band claimed that focus made every other measurement irrelevant.', rule: 'use Coherence while maintaining four active families', accessibility: 'The dominant ray is labeled by name, wavelength, thickness, and pattern.', rewardEffects: [{ kind: 'globalMult', value: 1.03 }] },
    { name: 'Dark Spectrum', failure: 'Absence was excluded from every civic instrument.', rule: 'complete a recipe using the Invisible Band', accessibility: 'Invisible output is represented by a bordered dark ribbon and text.', rewardEffects: [{ kind: 'critChance', value: 0.01 }] },
    { name: 'Broken Bench', failure: 'The public lens network lost every second optic.', rule: 'use alternating Kindling tiers only', accessibility: 'Available stations carry consecutive text labels and distinct shapes.', rewardEffects: [{ kind: 'clickShare', value: 0.002 }] },
    { name: 'No Shared White', failure: 'The factions refused synthesis even when extinction became visible.', rule: 'reach the target without White Synthesis', accessibility: 'All recipe state remains available as text and pattern.', rewardEffects: [{ kind: 'synergyMult', value: 1.05 }] },
    { name: 'Difference and Unity', failure: 'Unity was confused with a single surviving voice.', rule: 'finish with all six bands within ten percent balance', accessibility: 'Exact band quantities and imbalance percentages are announced.', rewardEffects: [{ kind: 'globalMult', value: 1.08 }] },
  ],
  tempo: 96,
  meter: '4/4 spectral pulse with six harmonic color families',
  audioFamilies: ['glass focus snap and photon hiss', 'rising lens interval', 'coherent harmonic flash', 'diffracted glass call', 'subtractive spectrum cadence'],
  silenceState: 'Every band remains readable through wavelength number, hatch pattern, ray thickness, and geometry.',
  fatiguePolicy: 'Focus snaps soften above four inputs per second; high partials are limited; Refraction removes bands before returning a restrained white chord.',
  routeGlyph: '◇',
  routeArrival: 'a white aperture opens, and six paths refuse to overlap before reaching it',
  unlockText: 'light Clockwork’s Beacon',
  beaconName: 'White Star Beacon',
  beaconSilhouette: 'white six-rayed star with separated patterned bands visible around its rim',
  beaconReward: 4,
  nonColorSignals: [
    { id: 'u5-coherence', text: 'coherence', shape: 'one thick vertical ray', pattern: 'solid narrow-band stripe' },
    { id: 'u5-synthesis', text: 'white synthesis', shape: 'six paths meeting a hexagon', pattern: 'bars, dots, crosshatch, waves, chevrons, outline' },
    { id: 'u5-fluorescence', text: 'fluorescence storage', shape: 'offset double contour', pattern: 'delayed dotted afterimage' },
    { id: 'u5-diffraction', text: 'diffraction', shape: 'fan of unequal rays', pattern: 'numbered maxima' },
  ],
}

const packs = createFutureUniversePack(PRISMATA_SPEC)

export const PRISMATA = packs.legacy
export const PRISMATA_V2_PACK = packs.v2
